"use client";
import {useEffect,useState} from "react";import{AnimatePresence,motion}from"framer-motion";
const slides=["/festher-hero.jpg","/festher-sunset-view.jpg"];
const services=[["✦","Festival","Festivals, Events & Celebrations"],["♢","Event Planning","Weddings, Birthdays & Corporate"],["♨","Food Service","Catering, Menus & Event Food"],["⌁","Tourism & Transport","Tours, Vehicles & Transfers"],["⌂","Hotel & Villa","Stay, Rooms & Hospitality"],["◇","Event Management","Complete Event Coordination"],["♜","Restaurant","Dine-in, Takeaway & Delivery"]];
const ServiceMenu=()=> <details className="services-menu"><summary>Services <span>⌄</span></summary><div className="services-dropdown"><div className="services-drop-head"><small>FESTHER SERVICES</small><strong>Our Services</strong><p>Explore everything FESTHER brings together in one place.</p></div><div className="services-drop-grid">{services.map(([icon,title,desc])=><div className="service-drop-item" key={title}><b>{icon}</b><div><strong>{title}</strong><small>{desc}</small></div><span>↗</span></div>)}</div></div></details>;
const Nav=()=> <nav className="navbar"><a href="/" className="brand"><span className="brand-name">FESTHER</span><span className="brand-tagline">Every Moment, A Celebration</span></a><div className="nav-links"><a className="active" href="/">Home</a><ServiceMenu/><a href="#packages">Packages & Offers</a><a href="#hotel">Hotel & Villa</a><a href="#restaurant">Restaurant</a><a href="/gallery">Gallery</a><a href="/about">About</a><a href="#contact">Contact</a></div><a href="#booking" className="nav-cta">Book now <span>↗</span></a></nav>;
const Ribbon=()=> <section className="service-ribbon"><div className="ribbon-label"><small>Discover</small><strong>FESTHER</strong></div><div className="ribbon-window"><div className="ribbon-track">{[...services,...services].map(([icon,title,desc],i)=><a href="#" className="ribbon-item" key={i}><span className="ribbon-icon">{icon}</span><span className="ribbon-copy"><strong>{title}</strong><small>{desc}</small></span><i>↗</i></a>)}</div></div><div className="ribbon-end">Plan · Stay · Dine</div></section>;
const Fade=({children,className=""}:{children:React.ReactNode,className?:string})=><motion.div className={className} initial={{opacity:0,y:35}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.15}} transition={{duration:.75}}>{children}</motion.div>;
export default function Home(){const[slide,setSlide]=useState(0);useEffect(()=>{const t=setInterval(()=>setSlide(v=>(v+1)%2),6000);return()=>clearInterval(t)},[]);return <main className="site-shell">
<section className="hero" id="home"><div className="hero-slides"> <AnimatePresence>{slides.map((src,i)=>i===slide&&<motion.div key={src} className="hero-slide" style={{backgroundImage:`url(${src})`}} initial={{opacity:0,scale:1.03}} animate={{opacity:1,scale:1.1}} exit={{opacity:0}} transition={{opacity:{duration:1.3},scale:{duration:7}}}/>)}</AnimatePresence></div><Nav/><div className="hero-content"><div className="hero-copy"><p className="eyebrow"><span/>A refined escape in Sri Lanka</p><h1>Where every stay<br/><em>becomes a story.</em></h1><p className="intro">Slow down, settle in, and discover a place where thoughtful stays, memorable dining and warm hospitality come together naturally.</p><div className="actions"><a href="#booking" className="primary-button">Book your stay →</a><a href="/gallery" className="ghost-button">Discover FESTHER</a></div></div></div><div className="hero-controls"><button onClick={()=>setSlide((slide+1)%2)}>←</button><span>0{slide+1} / 02</span><button onClick={()=>setSlide((slide+1)%2)}>→</button></div></section><Ribbon/>
<section className="home-stay" id="hotel"><Fade className="home-heading"><p className="section-kicker">Stay at FESTHER</p><h2>Rest beautifully.<br/><em>Wake up inspired.</em></h2><p>Thoughtful rooms and private spaces designed for slow mornings, peaceful evenings and effortless comfort.</p></Fade><div className="stay-layout"><motion.div className="stay-image" initial={{opacity:0,x:-40}} whileInView={{opacity:1,x:0}} viewport={{once:true}}><img src="/festher-hero.jpg" alt="FESTHER hotel and villa"/><span>Hotel & Villa</span></motion.div><div className="stay-options">{[["01","Family Rooms","Comfortable stays created for families and shared moments."],["02","Couple Retreat","A quiet, intimate escape for two."],["03","Entire Cottage","More space, more privacy, your own FESTHER experience."]].map(x=><article key={x[0]}><span>{x[0]}</span><div><h3>{x[1]}</h3><p>{x[2]}</p></div><b>↗</b></article>)}<a className="text-link" href="#">Explore Hotel & Villa →</a></div></div></section>
<section className="dining-home" id="restaurant"><div className="dining-image"><img src="/festher-sunset-view.jpg" alt="FESTHER dining atmosphere"/></div><Fade className="dining-copy"><p className="section-kicker">Signature Dining</p><h2>Gather. Taste.<br/><em>Remember.</em></h2><p>From relaxed meals to celebrations around the table, FESTHER brings warm service and memorable flavours into every dining moment.</p><div className="dining-tags"><span>Dine-in</span><span>Takeaway</span><span>Delivery</span><span>Event Catering</span></div><a className="primary-button" href="#">Explore Restaurant →</a></Fade></section>
<section className="packages-home" id="packages"><Fade className="center-heading"><p className="section-kicker">Curated for every occasion</p><h2>Packages & <em>Offers.</em></h2></Fade><div className="package-grid">{[["01","Romantic Escape","A quiet stay for two with time to slow down and reconnect."],["02","Family Getaway","Comfort, space and shared experiences for the whole family."],["03","Celebration Stay","Bring your special moments together with stay, dining and event experiences."]].map((p,i)=><motion.article key={p[0]} initial={{opacity:0,y:25}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.1}}><small>{p[0]} · FESTHER</small><h3>{p[1]}</h3><p>{p[2]}</p><a href="#">Discover package ↗</a></motion.article>)}</div></section>
<section className="why-home"><Fade className="why-title"><p className="section-kicker">Why FESTHER</p><h2>Everything you need.<br/><em>One memorable place.</em></h2></Fade><div className="why-grid">{[["⌂","Comfortable Stays"],["♨","Signature Dining"],["✦","Curated Experiences"],["♡","Warm Hospitality"]].map(([i,t])=><div key={t}><span>{i}</span><h3>{t}</h3><p>Thoughtful details, personal care and experiences created around you.</p></div>)}</div></section>
<section className="gallery-preview"><div className="preview-head"><div><p className="section-kicker">A glimpse of FESTHER</p><h2>See the <em>experience.</em></h2></div><a href="/gallery">View full gallery ↗</a></div><div className="preview-images"><img src="/festher-hero.jpg" alt="FESTHER property"/><img src="/festher-sunset-view.jpg" alt="FESTHER view"/><img src="/festher-hero.jpg" alt="FESTHER stay"/></div></section>
<section className="testimonials-home"><Fade className="center-heading"><p className="section-kicker">Guest stories</p><h2>Made to be <em>remembered.</em></h2></Fade><div className="review-grid">{["A beautiful place to slow down, celebrate and simply enjoy the moment.","Warm hospitality, a peaceful atmosphere and an experience we would happily return to.","From the setting to the service, every detail made our stay feel special."].map((r,i)=><blockquote key={r}><span>“</span><p>{r}</p><small>Guest Experience · 0{i+1}</small></blockquote>)}</div></section>
<section className="booking-home" id="booking"><p className="section-kicker">Your FESTHER story</p><h2>Your stay begins<br/><em>right here.</em></h2><p>Plan a peaceful stay, a memorable meal or a celebration worth remembering.</p><a className="primary-button" href="#contact">Start planning →</a></section>
<footer className="home-footer" id="contact"><div className="footer-brand"><span className="brand-name">FESTHER</span><p>Every Moment, A Celebration</p></div><div><small>Explore</small><a href="#hotel">Hotel & Villa</a><a href="#restaurant">Restaurant</a><a href="/gallery">Gallery</a><a href="/about">About</a></div><div><small>Experience</small><a href="#packages">Packages & Offers</a><a href="#">Events</a><a href="#">Food Service</a><a href="#">Tourism</a></div><div><small>Contact</small><p>Sri Lanka</p><p>Reservations & enquiries</p><a href="#booking">Book your stay ↗</a></div><div className="footer-bottom">© 2026 FESTHER <span>Every Moment, A Celebration</span></div></footer>
</main>}
